OP-1008 Clarify New Attendance and Re-Attendance fields
informatici/openhospital-doc pull request #186
Opened 2022-12-06 13:59 UTC by dbmalkovsky

See OP-1008

2022-12-06 14:36 UTC, mwithi requested changes
With the aim of better clarifyinf the two fields, I would put in the "OPD Extended" chapter, a reference to the **Type of attendance** above or... to write again a text including the "Re-Attendance" behavior

2022-12-07 20:33 UTC, dbmalkovsky commented
I've attempted to add additional information for the fields.

2022-12-07 21:58 UTC, mwithi commented on doc_user/UserManual.adoc
> + is under consideration is a new issue; that is, one that has not been dealt
```suggestion
 under consideration is a new issue; that is, one that has not been dealt
```

2022-12-07 21:59 UTC, mwithi commented on doc_user/UserManual.adoc
> + an issue or disease previously dealt with but not completely addressed (that
```suggestion
 with previously. For an issue or disease previously dealt with but not completely addressed (that
```

2022-12-07 22:02 UTC, mwithi approved these changes

2022-12-07 22:03 UTC, merged