OP-97 - anamnesis module
informatici/openhospital-doc pull request #187
Opened 2022-12-12 22:31 UTC by goto-eof

2022-12-13 12:18 UTC, dbmalkovsky commented on doc_user/UserManual.adoc
> +The medical history, case history, or anamnesis of a patient is information gained by a physician by asking specific questions, either to the patient or to other people who know the person and can gi
Suggested modified wording:
```suggestion
The medical history, case history, or anamnesis of a patient is information gained by a physician by asking specific questions either of the patient, or of other people who know the person and can give suitable information.  The aim is to obtain information useful in formulating a diagnosis and providing medical care to the patient.
```

2022-12-13 12:19 UTC, dbmalkovsky commented on doc_user/UserManual.adoc
> +To modify the anamnesis data of a patient select the patient in the *_Patient Browser_* window and then press the *[.underline]##E##dit* button. When the *_New Patient_* window is shown, then click o
Correction and slightly changed wording:
```suggestion
To modify the anamnesis data of a patient, select the patient in the *_Patient Browser_* window and then press the *[.underline]##E##dit* button. When the *_Edit Patient_* window is shown, click on the *_Anamnesis_* button and the record is available for changes. All the data can be changed.
```

2022-12-22 15:31 UTC, mwithi requested changes
It seems that `angal.anamnesis.patient` (the title) is missing.

I would also add changed screenshot where the button has been introduced (Admission/Patient, New/Edit Patient, New/Edit OPD) with link to the new chapter

2022-12-31 11:04 UTC, mwithi commented
Looks like the main screenshot has still the title missing.
For other screenshot where the "Anamnesis" button is missing, maybe we can just change the basic ones, like
- image14
- image78
- image85
- image92

wdyt @dbmalkovsky ?

2022-12-31 18:19 UTC, dbmalkovsky commented
image247:

- As noted, the dialog title is missing
- Make the capitalization consistent:   `Past problems (Closed)` -> `Past Problems (Closed)` and `Recent problems (Open)` -> `Recent Problems (Open)`
- Change  `DrugsAddiction` to `Drug Addiction`
- It would be nice not to have to use `Nr` as an abbreviation; could the line be something like `Number [ ]  Delivered [ ] Aborted [ ]`?
- Should the titles of the boxes on the right all be plural to match the rest of the dialog?

image78:
There is no shortcut key for the `Anamnesis` button; how about using `m` and changing the `Merge` button shortcut key to `g`?

imsge88p:
There is no shortcut key for the `Anamnesis` button; see above.

As for adding the button
image14:  yes
image78: already has the button
image85: see image88p; the button is there just some screen shots haven't been updated
image92: yes

2023-01-20 19:02 UTC, goto-eof commented
> 

done

2023-01-20 20:43 UTC, mwithi approved these changes
LGTM. Thanks a lot!

2023-01-20 21:31 UTC, merged