Op 1037 - remove administrative flag
informatici/openhospital-doc pull request #226
Opened 2023-05-20 09:29 UTC by goto-eof

2023-05-20 09:36 UTC, dbmalkovsky commented on doc_user/UserManual.adoc
> + In Open Hospital there are three types of Patient consent:
```suggestion
 In Open Hospital there are two types of Patient consent:
```

2023-05-20 09:36 UTC, dbmalkovsky commented on doc_user/UserManual.adoc
> +This consent should also be de-selectable, which implies the opt-out from the additional services (performed by the Patient Portal Connector)
```suggestion
This consent should also be de-selectable, which implies the opt-out from the additional services (performed by the Patient Portal Connector).
```

2023-05-20 09:37 UTC, dbmalkovsky commented on doc_user/UserManual.adoc
> +- Consent to additional services - to introduce a flag in the patient registration form to record the patient consensus for additional services (optional, for the Portal)
```suggestion
- Consent to additional services - to introduce a flag in the patient registration form to record the patient consensus for additional services (optional, for the Portal).
```

2023-05-20 18:15 UTC, mwithi requested changes
Please update the second consent as suggested, thanks!

2023-05-20 18:15 UTC, mwithi commented on doc_user/UserManual.adoc
> +This consent should also be de-selectable, which implies the opt-out from the additional services (performed by the Patient Portal Connector).
Why has been put like it was a requirement!? Please accept this suggestion

```suggestion
- Consent to additional services - consent to additional services means that the person consents to the use of the registered data for additional services, such as communications, mails, calls, follow ups reminders, digital services, etc. This field is NOT mandatory, but one hospital may decide to introduce it in its paper forms.
```

2023-05-20 19:16 UTC, mwithi commented
close because there was already https://github.com/informatici/openhospital-doc/pull/223

2023-05-20 19:28 UTC, mwithi approved these changes

2023-05-20 19:28 UTC, mwithi commented
Only screenshot missing and we are done! Thanks!

2023-05-23 20:01 UTC, mwithi commented
Superseded by https://github.com/informatici/openhospital-doc/pull/227

2023-05-23 20:01 UTC, closed without merging